name: Deploy AWS Lambda - Scan HTML

on:
  push:
    branches: ["main"]
    paths:
      - 'services/aws-lambda-scan-html/**'
permissions:
  id-token: write
  contents: read

env:
  AWS_ROLE: arn:aws:iam::380610849750:role/github-deploy-equalifyeverything-equalify
  AWS_REGION: us-east-2

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with: 
         sparse-checkout: | 
          services/aws-lambda-scan-html/
          shared/
          .github/workflows
         sparse-checkout-cone-mode: false

      - name: Build artifacts
        run: |
          cd ./services/aws-lambda-scan-html/
          npm ci
          npm run dist

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          role-session-name: github-deploy-aws-lambda-scan-html
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy Lambda Function
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          function-name: aws-lambda-scan-html
          code-artifacts-dir: ./services/aws-lambda-scan-html/dist
          handler: lambda.handler
          runtime: nodejs22.x
